language: php
sudo: false

cache:
  directories:
    node_modules
    vendor

matrix:
  include:
    - php: '5.2'
      dist: precise
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]]; then `phpenv global 5.3`; fi
  - composer install
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]]; then `phpenv global "$TRAVIS_PHP_VERSION"`; fi

install:
  - export DEV_LIB_PATH=vendor/xwp/wp-dev-lib
  - source $DEV_LIB_PATH/travis.install.sh

script:
  - source bin/travis.sh

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh
